language: node_js

# Sudo-enabled machines have much more memory
sudo: required

node_js:
  - node

before_install:
  # Prerequisite of Nightmare.js
  # https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # Install git-lfs
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.4.3/git-lfs-linux-amd64-1.4.3.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.4.3.tar.gz
  - mv git-lfs-1.4.3/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/

before_script: git lfs pull

script:
  - npm test
  - DEBUG=true npm run build

cache:
  directories:
    - fonts

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: releases
  api_key:
    secure: Irn5gzraLVLX2JwCIJtWcjO7mj9rj+u6EbczQYtfpif/Q7mS1L3En1IcTBwakqa1RYmIRzH/91HWMCDRIH6JMPjxdzcKsa+1BFtJys5/yzpMKT2JQIvBtydyqvCZ/vzIe1ehdvsqVEtaCGYipcEZjaS7dDNKjOAN1p1r2czxvt/5pPg2suLfse7lMEuimXDYDJUt4TbaNT1i1p6ygGZxTlBaoQ4AIWh4PqzoTAGmSJcr/pQoWycgDW60T4xujTajouWFEeW3xPOH5mLfAuwDL6egndqGMiBsFfVIJbICCjiz1Zn2p0/dcDKWT3M8qSf0QNoYk0aUzkL70Bn4roLFaqs3S0x5BRfu5o5eFbW9E6GafBjekB6uBRon68zutkCtTY+5nnrD64RtIhKbbTBY+9woO2U4AZCvv453hTd4HBpHFAlXE4J4SjprUW4cEP/6vqObD372/TwopdW/anCL7Ygj3Dd3I6HChBVsn1SPrFgCnOIiYnrNHKlyr941XSr0UUSQBsOzjGUFqjTysVAsdji6h5eQ0TD4V/wrJ1qtc+s77kDJIBP/fLNsHbfpxCzBmjkR/jR91TsJiSOev4WbkYouuQdU+nptBorpMwOuq2MFlIKbpxlix5bgnVJ1VmcRzYSiB+/WGfuxmdmcTYl48VsBxT5GolO+MV1j3grFDao=
  file:
    - bmp-1-poster.svg
    - bmp-1-poster.png
    - bmp-1-poster.pdf
    - bmp-2-poster.svg
    - bmp-2-poster.png
    - bmp-2-poster.pdf
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks: http://webhook.hakatashi.com/travis
